### PR TITLE
;Added connection with mySQL DB

### PR DESCRIPTION
**Pull request by DenyGurzhiy**
Hi,

There is a server with connection to mysql DB (in Docker container).

### CODE REVIEW

**Review by TatianaBortnik — APPROVED** [review]

**Comment by vikawal** [comment]
**** idea
A connection pool is a cache of database connections that are maintained so that the connections can be reused when new requests to the database are required.

When a new connection to a database is required, instead of creating a new connection each time, a connection from the pool is used. When the connection is no longer needed, it is returned to the pool instead of being closed. This allows the connection to be reused by another process, which greatly improves performance and reduces the load on the database server.

Connection pooling is particularly useful in high-concurrency environments, such as web servers and application servers, where many connections to the database are required simultaneously. By reusing existing connections, the number of connections that need to be created and closed is greatly reduced, which improves performance and reduces the load on the database server.
Something like this:

const fastify = require('fastify')();
const bcrypt = require('bcrypt');
const mysql = require('mysql2/promise');

const connection = mysql.createPool({
  host: 'localhost',
  user: 'root',
  password: '',
  database: 'mydb',
});

**Comment by tbazko** [comment]
@vikawal @DenyGurzhiy what Vika says is very valid point and an easy fix. @DenyGurzhiy please update this and then you can merge

**Comment by DenyGurzhiy** [comment]
> @vikawal @DenyGurzhiy what Vika says is very valid point and an easy fix. @DenyGurzhiy please update this and then you can merge

I did it, but already in other branch (signup). There is also pull request. @tbazko, what is the right way: to review and merge signup branch where was changed server connection part and created signup AP, or do it separately (to change here, and then review and merge signup request)? Thanks.

**Comment by vikawal** [comment]
Looks good. But I didn't read much about server. if it works - it's great. And yes, pool is done in other branch))) and we found out that it should be also closed, which we also did with help of Artem with draining before closing with watsons

**Review by tbazko — APPROVED** [review]

**Pull request merged**
